import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import { SpeedInsights } from '@vercel/speed-insights/next';
import '@/app/globals.css';
import { ThemeProvider } from '@/app/components';
import { Toaster } from '@/components/ui/sonner';
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar';
import { AppSidebar } from '@/app/components';
import { cookies } from 'next/headers';
import { themes } from '@/app/shared';
import { User } from '@/app/components/server/User';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};
export const metadata: Metadata = {
  title: 'yanyunchangfeng',
  description: 'Generated by yanyunchangfeng'
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar:state')?.value === 'true';

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange themes={themes}>
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar>
              <User />
            </AppSidebar>
            <SidebarInset className="overflow-x-hidden px-4">{children}</SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
        <SpeedInsights />
        <Toaster />
      </body>
    </html>
  );
}
